### ISSUE TITLE
0.1-latest fails in patching bc - spec.source.git: Invalid value: "": may not be set when binary is also set

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#11]
Timeout set to expire in 15 min
[Pipeline] {
[Pipeline] sh
[cleme-cd-be-node-express2-test] Running shell script
+ oc patch bc be-node-express2 --patch '
   spec:
     output:
       to:
         kind: ImageStreamTag
         name: be-node-express2:3-3beb5a91
     runPolicy: Serial
     source:
       type: Binary
     strategy:
       type: Docker
       dockerstrategy: {}
    ' -n cleme-test
The BuildConfig "be-node-express2" is invalid: 
* spec.source.git: Invalid value: "": may not be set when binary is also set
* spec.source.binary: Invalid value: "": may not be set when git is also set
[Pipeline] }

**Comment by clemensutschig** [comment]
https://jenkins-cleme-cd.<internal>/job/cleme-cd/job/cleme-cd-be-node-express2-test/3/console

**Comment by clemensutschig** [comment]
@michaelsauter - ok - templates where NOT up2date ... we need to get much better in managing those dependencies .. seriously.

Please add a note into the getting started guide on this - and then close

**Comment by michaelsauter** [comment]
@clemensutschig Yes, the shared library cannot patch the BC correctly for old templates atm. However, right now all users should be on the `latest` tag, and nothing should break for them. I want to write a migration guide how to move to the new `0.1-latest` tag, which involves updating the BC manually because the standard patch command does not work properly.

That said, I've been doing some reading on the patch command, and I think there is a solution to make it work automatically. I'll try that out - if it works, the migration is smoother.  If not, there is some manual work required. But so far the `0.1-latest` tag has not been advertised to anyone, so things should not break.
