### ISSUE TITLE
proper special characters management within ODS jenkins shared library and bash scripts

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-jenkins-shared-library#112]
This issues is created with the purpose to assure all possible special characters are properly handled within all the steps in ODS jenkins shared library and bash script calls.

See: Auto Clone Environment fails during curl download #109

**Comment by clemensutschig** [comment]
@henrjk  - can you do this for ODS 3?

**Comment by henrjk** [comment]
The title of this issue appears overly broad to me. 

The linked issue is about handling credentials when downloading the clone script, in

https://github.com/opendevstack/ods-jenkins-shared-library/blob/4f85b92f9d8d4954f0bca2807e37b50aeb7212ec/src/org/ods/component/Pipeline.groovy#L318

On the other hand I see a bunch of other curl calls:

```
$ grep -R -A 6 -n curl . 
./src/org/ods/component/Pipeline.groovy:318:                    script.sh(script: "curl --fail -s --user ${userPass} -G '${url}' -d raw -o '${scriptName}'")
..
./src/org/ods/component/Pipeline.groovy-323-                }
./src/org/ods/component/Pipeline.groovy-324-                userPass = userPass.replace('@', '\\@')
--
./src/org/ods/component/UploadToNexusStage.groovy:30:            script: "curl -u ${user} --upload-file ${distFile} ${uploadPath}",
./src/org/ods/component/UploadToNexusStage.groovy-31-            label: "Uploading ${distFile} to Nexus"
--
./src/org/ods/services/BitbucketService.groovy:48:                script: """curl \\
./src/org/ods/services/BitbucketService.groovy-49-                  --fail \\
./src/org/ods/services/BitbucketService.groovy-50-                  --silent \\
./src/org/ods/services/BitbucketService.groovy-51-                  --header \"Authorization: Bearer ${token}\" \\
./src/org/ods/services/BitbucketService.groovy-52-                  ${bitbucketUrl}/rest/api/1.0/projects/${project}/repos/${repo}/pull-requests?state=${state}""",
./src/org/ods/services/BitbucketService.groovy-53-                returnStdout: true
./src/org/ods/services/BitbucketService.groovy-54-            ).trim()
--
./src/org/ods/services/BitbucketService.groovy:70:                        script: """curl \\
./src/org/ods/services/BitbucketService.groovy-71-                            --fail \\
./src/org/ods/services/BitbucketService.groovy-72-                            --silent \\
./src/org/ods/services/BitbucketService.groovy-73-                            --request POST \\
./src/org/ods/services/BitbucketService.groovy-74-                            --header \"Authorization: Bearer ${token}\" \\
./src/org/ods/services/BitbucketService.groovy-75-                            --header \"Content-Type: application/json\" \\
./src/org/ods/services/BitbucketService.groovy-76-                            --data '${payload}' \\
--
./src/org/ods/services/BitbucketService.groovy:157:                script: """curl \\
./src/org/ods/services/BitbucketService.groovy-158-                  --fail \\
./src/org/ods/services/BitbucketService.groovy-159-                  --silent \\
./src/org/ods/services/BitbucketService.groovy-160-                  --user ${script.USERNAME.replace('$', '\'$\'')}:${script.PASSWORD.replace('$', '\'$\'')} \\
./src/org/ods/services/BitbucketService.groovy-161-                  --request PUT \\
./src/org/ods/services/BitbucketService.groovy-162-                  --header \"Content-Type: application/json\" \\
./src/org/ods/services/BitbucketService.groovy-163-                  --data '${payload}' \\
--
./src/org/ods/services/SonarQubeService.groovy:68:                script: "curl -s -u ${authToken}: ${hostUrl}/api/qualitygates/project_status?projectKey=${projectKey}",
```

@michaelsauter Is the code in BitBucketService already sound in your mind?

I would assume that the usage in SonarQubeService  is already ok because it is using a token which probably will only be made of benign characters.

In the UploadToNexus we should probably change the code so that the curl command sends a basic auth header which then in base64 encoding instead of trying to fight with arcane quoting rules.

**Comment by michaelsauter** [comment]
@henrjk Agree with the `SonarQubeService`, those were my thoughts as well. Regarding the `BitbucketService` - I mostly moved code, I suspect there still might be issues.

**Comment by henrjk** [comment]
I noticed that services in package `org.ods.orchestration.service` such as `NexusService` uses unirest-java (group="com.konghq"), module="unirest-java". 

Are there reasons why not to switch to Unirest in org.ods.services and (other places) where curl is currently used?

Apart form that I would think we should avoid curls --user option an instead build the basic auth header ourselves.

**Comment by michaelsauter** [comment]
@henrjk I think we can switch to Unirest. Only historically, the shared lib used `curl` (as it was not a global library, therefore unallowed to grab libraries).

**Comment by henrjk** [comment]
I looked more into `clone-project.sh` as well as the export and import scripts which are curl'ed in the shared library here:

https://github.com/opendevstack/ods-jenkins-shared-library/blob/c75bb9030b3ceee2bf31d54c65173056c4677a53/src/org/ods/component/Pipeline.groovy#L318

The userPass is problematic both from a security point of view but also because not all characters will work in the password.  In addition `userPass` is passed on to the `clone-project.sh` script as an argument.

https://github.com/opendevstack/ods-jenkins-shared-library/blob/c75bb9030b3ceee2bf31d54c65173056c4677a53/src/org/ods/component/Pipeline.groovy#L329

For backwards compatibility reasons `clone-project.sh` curls the export/import script to support shared libraries before version 2.x. For version 3.x I would believe this code can probably be removed.

`clone-project.sh` currently requires credentials to be passed although:
-  in interactive mode, credentials would be managed by the OS and/or asked about in a secure way. So it would be better if credentials were not required in this context.

I am leaning towards changing the clone code to write the bitbucket credentials into the netrc file so that the clone scripts could be oblivious regarding credentials. 

The export and import scripts interact with the repo via the `git` command line. If there are reasons not to use netrc I believe there are ways to establish a credential helper for each such command which would feed in the user/pw info via stdout/stdin. This would avoid any issues with special characters and also be more secure. 
For this the shared library could expose environment variables. However this approach is more involved and probably more fragile than the netrc approach. 

For curl I believe one could pipe in the password and only keep the url encoded username in the url.

@michaelsauter, @gerardcl:

1.  Do you think the netrc approach is viable and should be pursued?
2. Would it be safe to remove with respect to compatibility:

https://github.com/opendevstack/ods-core/blob/205f0e9f64f9c55d01ac9966ed9c02ef5f75870f/ocp-scripts/clone-project.sh#L112-L125

**Comment by michaelsauter** [comment]
@henrjk Thanks for the write-up. I would say we can remove the backwards compatibility layer, which gets us rid of the `curl` calls. Further, we already use the `netrc` approach already in the quickstarter pipeline: https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/quickstarter/PushToRemoteStage.groovy#L22-L25.

**Comment by henrjk** [comment]
I ran into issue #350 when end to end testing my changes in for this. Unfortunately this blocks  further progress  unless I would only focus on non autoclone scenarios, but for now I would put this on hold.

**Comment by gerardcl** [comment]
hi! sorry for delayed answer!

my thoughts: what about getting rid of the clone-script since that is something most of the times not able to be fully automatically used? (indeed: who is using it?) what about focusing on offering inter-namespace "cloning" approach when having different feature branches (I remember Michael already provided a way/example via tailor usage)? <- the more I think about this approach the more I think it makes sense also from a point of veiw of cluster-admin maintenance and also for quota management...

**Comment by michaelsauter** [comment]
@gerardcl Yes, the approach is described in https://www.opendevstack.org/ods-documentation/opendevstack/3.x/jenkins-shared-library/component-pipeline.html#_deploying_openshift_resources_from_source_code.

I agree with your statement. I am wondering if the clone script could be offered in `ods-contrib`. One might still want to run it manually, and then use the created namespace to deploy into. But I am not convinced it works well from within the component pipeline.

@henrjk @hugowschneider Thoughts?

**Comment by henrjk** [comment]
I am hesitating to kill auto cloning as it can be useful if you have the power to self provision. 

On the other hand making the feature work is costing a lot of time and it cannot be used in more restricted environments. 
Perhaps we should consider removing this in ODS 4 to have a bit more time for consumers to give feedback. We could mention this in the docs linked by @michaelsauter above in ODS 3.

In my opinion we should then get rid of the clone script entirely.
Perhaps we should even get rid of the export/import scripts or change them to use tailor. 

At any rate I think this issue is not just about cloning (check out the most recent PR version) so we should have a separate issue about the remove auto cloning discussion.

**Comment by michaelsauter** [comment]
@henrjk Sounds good to me. Let's revisit for v4.
