### ISSUE TITLE
Investigate using the DSL of jenkins-client-plugin

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#146]
Instead of shelling out to the `oc` binary we might be better of using the DSL of https://github.com/openshift/jenkins-client-plugin. This plugin is already installed in the Jenkins master.

Thanks @oalyman for the suggestion.

One downside of using that plugin is that it is harder to try out changes - instead of being able to play with commands in the terminal, right now I don't see a way other than running a pipeline to experiment with the DSL.

**Comment by michaelsauter** [comment]
@tjaeschke Ah! As far as I understand the DSL allows to fallback to "raw" commands for such cases.

**Comment by tjaeschke** [comment]
@michaelsauter This would be good. Hm, for experimenting locally with Jenkinsfiles I often use https://github.com/jenkinsci/jenkinsfile-runner since @ungerts recommended it to me a few months ago.

**Comment by michaelsauter** [comment]
@tjaeschke Awesome! I will definitely check this out. Maybe we can use this for tests as well?

**Comment by tjaeschke** [comment]
@michaelsauter I think so. On my agenda is also to take a look at https://github.com/jenkinsci/JenkinsPipelineUnit

**Comment by metmajer** [comment]
@tjaeschke @michaelsauter we've been successfully implementing roughly 200 unit tests for the MRO shared lib using just Spock. Why? Because when looking at frameworks targeted at pipeline unit testing, they had their fair share of limitations and had no major benefits over going with a solid general testing framework.

Also, it would be beneficial to settle on one approach for a type of tests. @tjaeschke know of a good framework for running integration tests against a live Jenkins instance?

**Comment by tjaeschke** [comment]
@metmajer I'm with you using Spock for unit testing. Unfortunately I didn't find any good framework for integration tests, that satisfied me, yet.

**Comment by rattermeyer** [comment]
oc patch was one thing. And having a complete mixture of DSL and raw things, we decided for one solution.
If looking, what seems to be available today (need still to check which version is included in the OpenShift images), using the DSL would be a real option.

**Comment by michaelsauter** [comment]
Everything has been moved into `OpenShiftService.groovy`, and right now I don't see issues with that approach so I'll close this for now.
