### ISSUE TITLE
ods-pipeline should have 2 more stages (start / finish)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#201]
**Describe the solution you'd like**
In order to verify odsPipeline did run w/o looking into the logs - we should add 3 more stages into the pipeline

namely
1. odsPipeline start (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/vars/odsPipeline.groovy#L5)
1. (rename) Prepare ods context (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsPipeline.groovy#L31)
1. odsPipeline finished (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsPipeline.groovy#L87-L90)
1. odsPipeline error (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsPipeline.groovy#L93-L112)

**Comment by renedupont** [comment]
I see a minor issue @clemensutschig 
If we want to echo a stage start info with componentId and gitBranch like for the other stages, we don't have the gitBranch info for the 'odsPipeline start' stage at that time since it gets determined later in the 'Prepare' stage.

**Comment by clemensutschig** [comment]
@renedupont  - NOT needed ... the stages should be named exactly as described above .. e.g. "odsPipeline start"

**Comment by renedupont** [comment]
After further discussion with @clemensutschig we decided to leave the first stage 'odsPipeline start' out and rename the 'Prepare' to 'odsPipeline start' instead of 'Prepare ods context'. The finished and error stages were implemented as desired.

start stage: https://github.com/opendevstack/ods-jenkins-shared-library/pull/202/files#diff-9b926a359deb3f339e040516225f076eR36
finish: https://github.com/opendevstack/ods-jenkins-shared-library/pull/202/files#diff-9b926a359deb3f339e040516225f076eR99
error: https://github.com/opendevstack/ods-jenkins-shared-library/pull/202/files#diff-9b926a359deb3f339e040516225f076eR107
