### ISSUE TITLE
ensure all credentials are masked in output logs

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#212]
there is still cases where credentials may not be masked (e.g. thru the ods-context).

**Comment by renedupont** [comment]
so far I only found the snyk auth token in the console output, what other credentials did you see?

**Comment by michaelsauter** [comment]
I think also the Nexus credentials can be exposed as they are not read via `withCredentials` :(

**Comment by renedupont** [comment]
@clemensutschig @michaelsauter 
After looking a bit into it I think the only quick fix without any changes on the user side would be to use 'set +x' in the shell cmd, e.g:

`    script.sh(
      script: """
                set +x
                snyk auth ${authCode} | tee -a ${reportFile}
              """,
      returnStatus: true,
      label: "Authenticate with Snyk server"
    )`

...that way it is not displayed in the output. It looks then like this:

`[Pipeline] sh (Authenticate with Snyk server)
+ set +x

Your account has been authenticated. Snyk is now ready to be used.`


btw. I found in Jenkins that if you open a build and click on the right side 'Pipeline Steps' (instead of 'Console Output') that all credentials are visible there in clear text... even the ones that are used within withCredentials. 
Any thought on this if this is critical or not?

**Comment by michaelsauter** [comment]
I think the most important thing is to avoid accidental credentials leakage. Therefore I'm ok with them being visible outside the build logs.

Regarding Snyk, it makes sense to do `set +x`, however we could also do the automatic transformation to a secret ... maybe we do `set +x` now because it is easy, and then do the secret in a next step.

**Comment by renedupont** [comment]
Yes I was thinking the same regarding the next steps...

but I just discovered that if you use Jenkins in the blue ocean view, it is all there in clear text :(
even when withCredentials was used.

**Comment by michaelsauter** [comment]
@renedupont wow. is that a known bug with the credentials plugin and/or blue ocean? that sounds like something the Jenkins community would try to fix, no?

**Comment by renedupont** [comment]
I don't know yet, this needs further investigation, but it looks like as if the blue ocean view is basically what you can see in the classic view if you click on 'Pipeline Steps'

**Comment by renedupont** [comment]
@michaelsauter I think I found out why the credentials are not masked when we use withCredentials... we use triple-double-quotation marks instead of triple-single-quotation marks in the sh call. 
Unfortunately, when using the single marks ('''), variables are not interpolated and something like USERPASS.replace(...) does not work that way when using '''. I tried out a lot of variants to still get it right that way but no luck yet.

**Comment by michaelsauter** [comment]
@renedupont Why is triple-double-quotes an issue? Do you have a reference?

**Comment by renedupont** [comment]
I tried it out because of the examples given here: https://jenkins.io/doc/pipeline/steps/credentials-binding/

**Comment by clemensutschig** [comment]
partially fixed by #329
