### ISSUE TITLE
Trim spaces and enters on cd-user secret ocp

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-jenkins-shared-library#392]
People by mistake add ending spaces or enters that gets them crazy to know what is going on, it will be nice if we trim the value

**Comment by clemensutschig** [comment]
@segator - you mean inside the secret? - if so - there is NOTHING that we can do about this ... because it's completely transparent to us ..

example:
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L216-L219
calls
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/GitService.groovy#L118

we would have to bake this into many places, assuming we even can /in the upper case impossible..

**Comment by segator** [comment]
yes you are right in first instance I tought on cases like docGen or some steps on the jenkisn shared lib but those that are direct and we can not do anything in the midle not possible :(

Thanks @clemensutschig
