### ISSUE TITLE
jenkins sends failed build status notifications to undesired recipients

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-jenkins-shared-library#449]
**Describe the bug**
When having `notifyNotGreen` enabled (default setting) Jenkins sends failed build notification emails to non expected recipients. The issue seems related to be using too much recipients options when defining recipients list in the library. See:

```
to: script.emailextrecipients([
                [$class: 'CulpritsRecipientProvider'],
                [$class: 'RequesterRecipientProvider'],
                [$class: 'UpstreamComitterRecipientProvider']
            ])
```

**To Reproduce**
1. Using ODS 3.x, make a jenkins pipeline fail
2. E-mails are sent to much more emails like: noreply@github.com <noreply@github.com>, unknown@boehringer-ingelheim.com <unknown@boehringer-ingelheim.com>

**Expected behavior**
The e-mails recipients should be less wide by default and also configurable from a user point of view.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.x, master

**Comment by michaelsauter** [comment]
in ODS 3.x email recipients are defined like this:
 
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L313-L321
 
Meaning failed build trigger mails to CulpritsRecipientProvider, RequesterRecipientProvider, UpstreamComitterRecipientProvider.
 
Those have slightly different names on https://www.jenkins.io/doc/pipeline/steps/email-ext/ , but my understanding is that we map to the following groups, with the following description:
 
Culprits = Sends email to the list of users who committed a change since the last non-broken build till now. This list at least always include people who made changes in this build, but if the previous build was a failure it also includes the culprit list from there.
Requestor = Sends email to the user who initiated the build.
UpstreamDevelopers = Sends email to the list of users who committed changes in upstream builds that triggered this build.
 
ODS 2.x also included „Developers = Sends email to all the people who caused a change in the change set.“ I removed this in https://github.com/opendevstack/ods-jenkins-shared-library/pull/309, to avoid getting emails from failed builds.
 
Now if I read the description on the email-ext website again, I could imagine that the very first build after an upgrade from 2.x to 3.x in a project might “see” the ODS Jenkins Shared Library changes as part of the „Culprits“.
 
In any case, ODS 3.x should send LESS, not MORE emails ... or am I really confused?

**Comment by gerardcl** [comment]
documentation related to this change is tackled and fixed here https://github.com/opendevstack/ods-core/issues/827
