### ISSUE TITLE
Sonarqube report - code analysis always based on application's master branch

### ISSUE THREAD

**Issue by jssnull** [opendevstack/ods-jenkins-shared-library#491]
Currently in ODS 3.x and ODS 2.x, If we use Docgen for generate documentation for a quickstarter using a branch different than master in the quickstarter, a document generated (SSDS document) will contain sonarqube analysis info from quickstarter's master branch instead of branch used by quickstarter.

For example, if we use docgen for generate documentation for a python quickstarter concretely from quickstarter develop branch, the resulting SSDS will contain in "Code Analysis" section sonarqube reports made from quickstarter master branch instead of develop branch (which was the choosen branch in Docgen).

We also noticed that, in this case docgen, generates successfully the sonarqube scan succesfully for develop branch.

**For explaining this case, we'll provide the following example:** 
* Docgen with only one application
* python application with two branches:
   * master (contains 7 lines of code in main application)
   * develop (contains 9 lines of code in main application)

**Setup used for reproduce this case:**

**Release manager metadata.yml file:**
<img width="157" alt="metadata" src="https://user-images.githubusercontent.com/12979859/99542928-e3575100-29b2-11eb-8d91-3ddda0206cee.PNG">

**Sonar .properties file (generates in execution time the branch used, project name, etc)**
<img width="334" alt="sonar-config" src="https://user-images.githubusercontent.com/12979859/99543181-2d403700-29b3-11eb-8457-51347fdead8b.PNG">

**Custom stage for configure sonar config in execution time:**
<img width="575" alt="sonar-prepare" src="https://user-images.githubusercontent.com/12979859/99543214-3a5d2600-29b3-11eb-90d9-32bdf8cd5327.PNG">

**We also make sure our sonar config is generated in the proper time:**
<img width="278" alt="stage_declaration_order" src="https://user-images.githubusercontent.com/12979859/99543530-8f00a100-29b3-11eb-800d-b0c9d0657f57.PNG">

**We also checked OpenDevStack docs for this task:**
https://www.opendevstack.org/ods-documentation/opendevstack/3.x/jenkins-shared-library/orchestration-pipeline.html#_automated_generation_of_compliance_documents
and applyed the following param to our jenkinsfile:

<img width="200" alt="sonarqube-branch" src="https://user-images.githubusercontent.com/12979859/99543676-b7889b00-29b3-11eb-854a-2b14479f4db6.PNG">

**After running Docgen, we see that our sonarqube scan was performed properly in application develop branch:**
<img width="461" alt="sonarqube-ui-main" src="https://user-images.githubusercontent.com/12979859/99544049-26fe8a80-29b4-11eb-8d02-62d5638de204.PNG">

**We can check the develop branch scan report:**
<img width="680" alt="sonar-develop-coverage" src="https://user-images.githubusercontent.com/12979859/99544228-5a411980-29b4-11eb-8e8f-adc5e71eb835.PNG">

**If we check the resulting SSDS Code Analysis section, we see the resulting report is coming from latest master branch codescan:**

<img width="568" alt="SSDS" src="https://user-images.githubusercontent.com/12979859/99544498-aab87700-29b4-11eb-8498-6089e07572f7.PNG">

**master branch code scan:**
<img width="679" alt="sonar-master-coverage" src="https://user-images.githubusercontent.com/12979859/99544574-c15ece00-29b4-11eb-8227-69f144d82ea9.PNG">

How we can solve this?

Best Regards

**Comment by felipecruz91** [comment]
The issue is due to the order in which the following code gets executed:

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/ScanWithSonarStage.groovy#L22-L25

If the branch is defined in the `sonar-project.properties` file, then it will ignore the `sonarQubeBranch` property from the context.

**Comment by clemensutschig** [comment]
@felipecruz91  - I am talking about the report generation - that goes against master ..... (see comments above)

**Comment by clemensutschig** [comment]
@renedupont  - do you want to try?

**Comment by renedupont** [comment]
@clemensutschig yes I can take a look on friday. 
One question though, is the Developer Edition requirement (for using --branch) of sonarqube not a blocker for ODS? Or do we already have this as a requirement?

**Comment by clemensutschig** [comment]
We run both - I would expect that this works in a corp context - and then shows the branch :) and developer edition - to show master ...

**Comment by michaelsauter** [comment]
Also note that the Jenkins master image has an environment variable containing the edition in use: https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/build/bc.yml#L104. IIRC we already use this to determine whether pull request analysis can be performed (which is also not available in the community edition).

**Comment by renedupont** [comment]
@michaelsauter @clemensutschig 
I tried to test the behaviour of cnesreporter's `--branch` flag in a sonarqube community and developer edition but had issues to use it at all. 
Apparently, as it turns out, we are currently not really using the branch feature of Sonarqube at all. Sonarqube has its own sonar branches, which are NOT automatically created when you scan a branch other than master. So no matter what someone writes in the Jenkinsfile as eligible branches as param to the sonar stage (even` [branch: "*"]`), it will end up in sonarqube under the sonar brach `master`. 
To create a sonar branch, we need to provide the property `sonar.branch.name` (see [doc](https://docs.sonarqube.org/latest/branches/overview/)). I tried it and in the UI you will get a drop down of all scanned branches for a project where you can select the desired.

Dealing with the above is a prerequisite for fixing the `--branch` cnesreport issue. I think the implementation will be straightforward (just adding `-Dsonar.branch.name` to the stage scan method?) and I'll hopefully be able to do it on monday. 
The only concern I have is that it will be easy to mix these sonar branches with what we call eligible branches, no?

**Comment by renedupont** [comment]
Also, while testing I figured that the `--branch` will probably not work for community editions because if the given branch does not exist the cnesreport will return with error a la `Error {"errors":[{"msg":"Component 'rene-quarkus' on branch 'bugfix/cnesreport-branch' not found"}]}`

**Comment by clemensutschig** [comment]
Hey @renedupont cool! - take a look above (at the very beginning) - this contains the fix for `sonar.branch`- as well ... we could check for the flag @michaelsauter  mentioned, to see if we are on community, or not ...

**Comment by metmajer** [comment]
@renedupont, @clemensutschig put this from Done into To Do for ODS 3.1, but looking at #506 this is Done, correct?

**Comment by clemensutschig** [comment]
@renedupont the agent update für 3.x is done as well.. Le?

**Comment by renedupont** [comment]
@metmajer yes
@clemensutschig https://github.com/opendevstack/ods-core/pull/894

**Comment by metmajer** [comment]
Thanks!
