### ISSUE TITLE
Can we do vulnerability checks on Docker images?

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#50]
Not sure if the build pipeline is the best place, but maybe we can check Docker images, e.g. using Clair: https://github.com/coreos/clair/.

**Comment by rattermeyer** [comment]
Actually, that is something that is on our list as well. Idea the same. Currently, I only see build pipeline. Otherwise, we would need to integrate an external repo like VMWare Harbor. Which has other implications.

**Comment by michaelsauter** [comment]
In London, I saw references of:

* https://github.com/aquasecurity/kube-bench
* https://github.com/aquasecurity/microscanner
* https://github.com/aquasecurity/kube-hunter

Those are free to use, but I have not looked into them yet, just adding the links here as possibly helpful ...

**Comment by clemensutschig** [comment]
@stitakis is on this

**Comment by stitakis** [comment]
I see here 2 requirements:
A. extend CI/CD build pipeline to support docker image scanning stage with support for different vendors/tools:
Challenges:
- scanning time should not impact too much the duration of the build, otherwise it will slow down it
- alternatively if scanning time is too long we could only activate it for merges to master. 

B. find best docker scanning tool that integrates in openshift

At BIX I´m doing a proof of concept of docker scanning tools and integration in ODS, atm we are testing one vendor solution that provides docker scanning checks but also for 3rd party libs and open source licenses

**Comment by gerardcl** [comment]
Hi! we could also make use of the github security provided features, see more here --> https://github.blog/2019-05-23-introducing-new-ways-to-keep-your-code-secure/

**Comment by clemensutschig** [comment]
Snyk @titakis

gerardcl <notifications@github.com> schrieb am Fr., 19. Juli 2019, 21:30:

**Comment by gerardcl** [comment]
Hi @clemensutschig , my previous comment is independent of an integrated solution but stating that we can also/moreover make use of github services :)
have we looked into them?

**Comment by rattermeyer** [comment]
@clemensutschig : that is one option. we should make an interface that allows to plug in different solutions. for the open source version clair / owasp would be an option. snyk is only one option for the commercial ones. should allow companies to make their own decisions
@gerardcl : we are using it already on our company repos. would totally make sense to enable this on the opendevstack org repos. I also like the dependabot, because it generates PRs and thus allows all to quickly address the issue. On the other side, it shows your vulnerabilities. the security alerts can be shown only to limited group of users.

**Comment by renedupont** [comment]
just a status update: we are currently looking into aqua security ( the full suite with runtime protection etc.) but I was also recently made aware of that Snyk offers now container vulnerability check (https://support.snyk.io/hc/en-us/categories/360000583498-Snyk-Container) I might look into this additional soon. Maybe have it as an additional stage after the oc image build stage?

**Comment by renedupont** [comment]
The plan is now to integrate with Aqua Security. Issues for this will be created once this will be tackled.

IMO we can close that ticket. Any objection @michaelsauter ?

**Comment by michaelsauter** [comment]
Sounds good!
