### ISSUE TITLE
TIP & TIR documentation for a library component is not entirely correct

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#605]
**Describe the bug**
There's a use-case where Release Manager is used to generating documentation for a Python library. The component pipeline is quite simple, composed of a single stage:

- Uploading the library to Nexus (so other Python components can import it)

Notice I have commented out the stage `odsComponentStageRolloutOpenShiftDeployment()` in the component pipeline as it doesn't make sense to deploy a library to OpenShift because of its own nature.

(See https://github.com/opendevstack/ods-jenkins-shared-library/issues/603 for more detailed information).

**To Reproduce**
1. Create a Python Quickstarter
2. Edit the Jenkinsfile to just package and upload the library to Nexus. Remove the `odsComponentStageRolloutOpenShiftDeployment()` stage.
3. Make a first deployment with Release Manager.
4. Rename the `openshift-exported` folder to `openshift` and empty the `openshift/template.yml` file:
```yaml
apiVersion: template.openshift.io/v1
kind: Template
objects:
parameters:
- name: TAILOR_NAMESPACE
  required: true
- name: ODS_OPENSHIFT_APP_DOMAIN
  required: true
```
5. Remove the OpenShift resources (DeploymentConfig, Service, Routes, etc) that were created by the first deployment in OpenShift as it doesn't make sense to deploy a library to OpenShift.

**Expected behavior**
I'd expect both the TIP and TIR documents to represent the reality. Especially the TIR document (see screenshot below), where it says:

`POD is running for 5 min` and `Route is accessible via HTTP`: `pass`

That's not correct as the Library neither has been deployed to OpenShift (it has been only uploaded to Nexus) nor has a Route (it was deleted in Step 5).

**Screenshots**

Excerpt from the Technical Installation Plan (TIP)
![image](https://user-images.githubusercontent.com/15997951/111126416-f6e68300-8572-11eb-9f8a-6409b1d76dae.png)

Excerpt from the Technical Installation Report (TIR)
![image](https://user-images.githubusercontent.com/15997951/111124590-f5b45680-8570-11eb-9fb6-600125c500f6.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.1
 
**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Log output here...
```

**Additional context**
Background: https://github.com/opendevstack/ods-jenkins-shared-library/issues/603

/cc @metmajer

**Comment by metmajer** [comment]
Hi @felipecruz91, this deserves some clarification.

- The TIP (plan document) makes a generic claim that the component will be successfully deployed and installation tested. For the result, the TIP refers to the TIR (report document). TIP is good.
- The TIR is also correct, since a service is equipped with a Readiness/Liveness Probe. In your case the claim in the TIR wrong, since you actually don't deploy anything, including the probes. The TIR does not foresee this. However, note that the TIR does not get generated in case of a pipeline error.

Hope this helps. We need to find out if a library shall use an ODS Component or not, and how a library would be validated as part of a use-case in Jira. FYI @clemensutschig

**Comment by metmajer** [comment]
@felipecruz91 please close the issue if you agree with the explanation above.
