### ISSUE TITLE
SonarQube integration with Git repository (PR decoration)

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#665]
This feature will make the result of Sonarqube scan for the Pull request made in a repository available directly from the Git repository, without the necessity to access SonarQube (except if you want to see the full report of the scan).
> Sonar Documentation about PR decoration: https://docs.sonarqube.org/8.2/analysis/pr-decoration/

### Requirements:

- Configure ALM integration in Sonarqube for a Git repository (Bitbucket, Github, Gitlab...)
 
![image](https://user-images.githubusercontent.com/26645694/121681256-e040c100-caba-11eb-9497-7b1698bc6626.png)

- Configure the Sonar project to make use of PR decoration

![image](https://user-images.githubusercontent.com/26645694/121681649-5e9d6300-cabb-11eb-8623-89b813d35164.png)

Right now this requirements are needed to be done manually, even the 2º needs to be done for each project in SonarQube but the Shared library should be able to do this for SonarQube editions Developer and above when each project in Sonarqube is created

When this configuration is done and we create a PR in our Git repositories it will look like this:
![image](https://user-images.githubusercontent.com/26645694/121683830-33684300-cabe-11eb-868b-1b8941d9c67b.png)

We will be even able to see the warnings from Sonarqube directly in the Diff in the PR:
![image](https://user-images.githubusercontent.com/26645694/121683120-3b73b300-cabd-11eb-899e-708a7f2bf30a.png)

@metmajer @felipecruz91 @borja44

**Comment by michaelsauter** [comment]
Hi, isn't that exactly what's already been implemented? :) See https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/SonarQubeService.groovy#L36-L46.

Note that the one limitation with this is that the PR needs to exist at the time the pipeline runs. That requires the developers to create the PR before pushing. To circumvent that issue we'd need to run pipelines on `pr:opened` events as well ...

**Comment by braisvq1996** [comment]
I don't think that is the same, at least, the PR decoration in our Bitbucket repositories is not happening unless we follow the requirements I mention above.

**Comment by metmajer** [comment]
@michaelsauter I prefer the way we are integrating Aqua with Bitbucket: each commit on a component is decorated with SonarQube scan results. We should follow the same approach here.

@renedupont and @michaelsauter since you were involved in the SonarQube integration, do you have any feedback on creating a similar approach? Do you have cycles to support us while we finish the Aqua integration?

FYI @s2oBCN @jorge-romero @hrcornejo @borja44 @segator

**Comment by michaelsauter** [comment]
I can only repeat that all that is mentioned above is already implemented. The Aqua integration (attaching a code report) is actually based on the SonarQube integration: I tried to figure out how SonarQube is doing it, found out about code insights, and suggested to do the same for Aqua.

The code snippet I linked above sets all the parameters which can be seen in the screenshot. When we released 3.x the code insight and the PR integration worked out of the box with no config in SQ necessary.

If this does not work right now I suggest to investigate ... maybe something changed in a newer SQ version?

**Comment by renedupont** [comment]
AFAIK this is the issue in that Michael implemented this in the past: https://github.com/opendevstack/ods-jenkins-shared-library/issues/174

**Comment by metmajer** [comment]
@borja44 I had specifically mentioned that we want to see the use of the existing integration into ODS, which was recently fixed via https://github.com/opendevstack/ods-core/issues/966.

@braisvq1996 the screenshots you show depict an integration between the SonarQube server and Bitbucket, which would be an alternative to the ODS integration.

**Comment by clemensutschig** [comment]
@renedupont  - can you provide screenshots how this currently looks like?

**Comment by clemensutschig** [comment]
@braisvq1996 - can you share your jenkinsfile setup (and SQ scan stage config)?

**Comment by michaelsauter** [comment]
OK some googling revealed https://community.sonarsource.com/t/bitbucket-server-pr-decorator-fails-to-use-scanner-properties/17217. Unfortunately it does not say which version this is. But I guess right now that in 7.9 (LTS) it worked but in 8.2 it does not work anymore. Now the question is if we can get it to work by providing a global config (Bitbucket Server URL and token) and then selecting that one from the scanner invocation.

**Comment by clemensutschig** [comment]
@michaelsauter - there is an interesting comment:

```
Either by updating to the SQ 8.2 and creating your project from the UI by selecting a BitBucket Server or by calling the webAPI api/alm_integrations/import_bitbucketserver_project
```

maybe we can call the API during quickstarter provisioning=?

**Comment by braisvq1996** [comment]
This is the error we get in SonarQube when trying PR decoration without the configuration mentioned about at the start of the issue:

```
Pull request decoration did not happen. Configuration missing to decorate the Bitbucket Server pull request: BitbucketServerPrConfiguration{serverUrl=null, project='alphatest2', repository='alphatest2-pythontest', id=1, headSha='ZZZZZZZZZZZZZZZZZZZZZZZZ', token=null}
```

**Comment by clemensutschig** [comment]
you could try to call
<sonar>/web_api/api/alm_integrations?deprecated=true&internal=true&query=import_bitbucketserver_project

and then also setting the pat .. maybe that does the trick?

**Comment by clemensutschig** [comment]
I talked with @michaelsauter about this .. the sq wide setting we could do during the setup of sq .. and project setting needs to happen either in the quickstarter or component pipeline

**Comment by renedupont** [comment]
@clemensutschig The Bitbucket Code Insight feature used for the aqua integration consists basically just of a link to the report on the aqua server: 
![pic](https://user-images.githubusercontent.com/39172761/121901858-11bdc480-cd27-11eb-8c2e-f0cc939ceb93.png)

**Comment by metmajer** [comment]
@braisvq1996 which permissions were you using before?

**Comment by braisvq1996** [comment]
We need to be admin of the Sonarqube Project we want to edit:

Bind a Bitbucket ALM instance to a project.
If the project was already bound to a previous Bitbucket ALM instance, the binding will be updated to the new one.**Requires the 'Administer' permission on the project**

**Comment by segator** [comment]
it will be nice if we can update prov-app so instead of calling to specific user jenkins project is calling to jenkins master(there we can have admin accounts) then we apply all the needed actions like create sonarQ project, configure ALM and any high administrative task, afterward we call to specific jenkins project as we are doing now.
This should be easy to implement playing with webhook proxy calls.
@metmajer  what do you think? this will fix the issue and is a solution for any other processes that require admin accesses for component provisioning.

**Comment by braisvq1996** [comment]
@segator, One thing to take into account if we do it is that the PVC for Jenkins-master will be filled up quickly as there would be more Pipelines stored there

**Comment by braisvq1996** [comment]
@metmajer @clemensutschig @michaelsauter 

Another option could be to use this api call: ```POST api/alm_integrations/import_bitbucketserver_project```
https://next.sonarqube.com/sonarqube/web_api/api/alm_integrations/import_bitbucketserver_project?internal=true&query=import_bitbucketserver_project

This will import the project from Bitbucket and configure PR decoration for the project. It only needs 'Create Project' permissions

**Comment by metmajer** [comment]
@braisvq1996 @michaelsauter @clemensutschig @segator we cannot go live with ODS 4.x in July without an automated solution. has someone evaluated the most simple and effective solution for an implementation or is this still not clear?

**Comment by clemensutschig** [comment]
the bitbucket project is created from the admin jenkins in the ods namespace - so maybe your idea (@braisvq1996 could work).. BUT .. what rights are needed, for bitbuckets project we have rights (As we create it there) - but what else?

and secondly - what happens if repos are added (via quickstarters from the specific project jenkins)..

**Comment by clemensutschig** [comment]
so here is my idea: take the token out of the project and also the secret data - and see if you can call the API 🗡️

**Comment by clemensutschig** [comment]
> An update, it seems that the SonarQube token does not have enought rights to set the PR decoration into the project with the api call mentioned by @clemensutschig :
> 
> ```
> {"errors":[{"msg":"Insufficient privileges"}]}sh-4.2$
> ```
> 
> If we try with the admin account it does work
> @michaelsauter

what account are you talking about ?

**Comment by clemensutschig** [comment]
@renedupont and I tried ...

a) ONE bitbucket integration per SQ instance (that means you need a "super user with write everwhere :("
b) only then you can call import .. (with u/pw)

**Comment by clemensutschig** [comment]
indeed - and it needs a global write BB user :(

**Comment by braisvq1996** [comment]
Also I have been trying to use the api I last mentioned ```POST api/alm_integrations/import_bitbucketserver_project```
But in our DEV environment It seems that the connection between SonarQube and Bitbucket is blocked somewhere so I have not been able to test it yet

**Comment by clemensutschig** [comment]
ha @renedupont  found out  that on enterprise edition you can create multiple bb integrations (which could mean for us to create one per edp project) from ods' jenkins - the problem we have is the SQ token in each project has no username /pw which you would need to auth for the binding

**Comment by braisvq1996** [comment]
@clemensutschig it is posible, but if we go for that option it could be possible that we cannot import projects from Bitbucket:
https://docs.sonarqube.org/8.2/analysis/pr-decoration/

![imagen](https://user-images.githubusercontent.com/26645694/123298227-932c0880-d518-11eb-8e0c-bfcc929f7284.png)

**Comment by michaelsauter** [comment]
I have experimented with the idea of doing the pull request decoration ourselves from the shared lib. In this scenario, we would run the SonarQube scan, then query the SQ API for results, and then use this result to attach a code insight to Bitbucket. The advantage of that approach would be that SQ does not need permissions in Bitbucket at all.

The scanner invocation would change from:
```
sonar-scanner -Dsonar.host.url=https://example.com -Dsonar.auth.token=****** -Dsonar.scm.provider=git -Dsonar.projectKey=michael-sample-app -Dsonar.projectName=michael-sample-app -Dsonar.projectVersion=8f372324 -Dsonar.pullrequest.provider=Bitbucket Server' -Dsonar.pullrequest.bitbucketserver.serverUrl=https://bitbucket.bix-digital.com -Dsonar.pullrequest.bitbucketserver.token.secured=**** -Dsonar.pullrequest.bitbucketserver.project=michael -Dsonar.pullrequest.bitbucketserver.repository=michael-sample-app -Dsonar.pullrequest.key=4 -Dsonar.pullrequest.branch=feature/pr-analysis-test -Dsonar.pullrequest.base=master
```

to this:
```
sonar-scanner -Dsonar.host.url=https://example.com -Dsonar.auth.token=****** -Dsonar.scm.provider=git -Dsonar.projectKey=michael-sample-app -Dsonar.projectName=michael-sample-app -Dsonar.projectVersion=8f372324  -Dsonar.pullrequest.key=4 -Dsonar.pullrequest.branch=feature/pr-analysis-test -Dsonar.pullrequest.base=master
```

Basically cutting all `-Dsonar.pullrequest.bitbucketserver.*` parameters.

Once we have this, we can query the SQ API for information. In order to achieve feature parity with the integration provided by SQ we'd need to get comments on source lines changed in the PR. I was not able to find an endpoint that does that. `GET api/sources/lines` is close (it has line information with e.g. coverage) but it does not have findings per line. More importantly, it is internal and I think we should avoid these - internal APIs may change or be removed without warning. An example response of that endpoint:
```
{
  "sources": [
    {
      "line": 4,
      "code": "\t<span class=\"s\">\"fmt\"</span>",
      "scmRevision": "",
      "scmAuthor": "",
      "scmDate": "2021-02-26T10:19:20+0000",
      "duplicated": false,
      "isNew": false
    },
    {
      "line": 13,
      "code": "\tfmt.Println(quote.Hello())",
      "scmRevision": "",
      "scmAuthor": "",
      "scmDate": "2021-02-26T10:19:20+0000",
      "utLineHits": 0,
      "lineHits": 0,
      "duplicated": false,
      "isNew": false
    }
  ]
}
```

Apart from source code level info, we have a few API endpoints with higher-level info:

One is `GET api/measures/component?component=michael-sample-app&pullRequest=4&metricKeys=ncloc,complexity,violations`:
```
{
  "component": {
    "id": "AXpCXju-x_mCpeFyltf6",
    "key": "michael-sample-app",
    "name": "michael-sample-app",
    "qualifier": "TRK",
    "measures": [
      {
        "metric": "violations",
        "value": "0",
        "bestValue": true
      }
    ],
    "pullRequest": "4"
  }
}
```
Sometimes there are more measures, seems to depend on the state.

Then we have `GET api/components/app?component=michael-sample-app&pullRequest=4`:
```
{
  "key": "michael-sample-app",
  "uuid": "AXpCXju-x_mCpeFyltf6",
  "name": "michael-sample-app",
  "longName": "michael-sample-app",
  "q": "TRK",
  "project": "michael-sample-app",
  "projectName": "michael-sample-app",
  "pullRequest": "4",
  "fav": false,
  "canMarkAsFavorite": true,
  "measures": {
    "coverage": "0.0",
    "duplicationDensity": "0.0",
    "issues": "0.0"
  }
}
```

Finally, and probably best fitting is `GET api/project_pull_requests/list?project=michael-sample-app`:
```
{
  "pullRequests": [
    {
      "key": "4",
      "title": "Jenkinsfile edited online with Bitbucket",
      "branch": "feature/pr-analysis-test",
      "base": "master",
      "status": {
        "qualityGateStatus": "OK",
        "bugs": 0,
        "vulnerabilities": 0,
        "codeSmells": 0
      },
      "analysisDate": "2021-06-25T08:51:45+0000",
      "url": "https://bitbucket.example.com/projects/MICHAEL/repos/michael-sample-app/pull-requests/4",
      "target": "master"
    }
  ]
}
```

I think this last one could be fed into a Bitbucket code insight to at least get high-level feedback and a link to the detailed SQ report.

Thoughts?

**Comment by clemensutschig** [comment]
awesome!

**Comment by metmajer** [comment]
You're the man @michaelsauter, thanks for the findings!

**Comment by metmajer** [comment]
@michaelsauter @braisvq1996  @clemensutschig since our team has finished the integration between Aqua and Bitbucket, we can take on this topic and include it in the ODS 4.0 release.

**Comment by michaelsauter** [comment]
@metmajer How do you intend to solve this?

I see two ways forward:

1) Providing a minimal solution
That would be using some of the endpoints I show above to at least get the high-level metrics for the PR. This misses line-level comments the PR, but is implementable without huge effort I believe.

2) Providing a more ideal solution
The best user experience would be to have line-level comments and if we want to avoid crazy stuff, the obvious way to achieve that is to use the SQ built-in decoration mechanism, which requires an admin call to setup ALM integration on ODS project creation, as well as an admin call to connect a repo to an ALM integration on ODS component creation. This is not easy to achieve right now as the architecture is not setup for it, but I think long-term this would be the right choice.
I think in general, the SonarQube setup is quite poor in terms of access control. The ideal setup would have RBAC that would mirror the permissions in Bitbucket. For this, the provisioning mechanism of projects/components would need admin permissions in SonarQube. An additional hurdle is that it would also need a project-specific personal access token for Bitbucket in order to create the ALM integration per-project.

**Comment by metmajer** [comment]
@michaelsauter I am currently aiming for the minimal solution you provide. A deeper integration with line-level information does not seem to be feasible using REST, but hey, then it won't be available in the next release. Do you know if the SonarQube report contains these information at least? We'd ensure similar behavior with Aqua, meaning that a scan report would also be exported and stored in Nexus. We can work out a more ideal solution together with our team members once ODS 4.0 has been delivered. I don't regard this solution to be feasible in July.
