### ISSUE TITLE
Aqua scanner stage does not have timeout

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#899]
**Is your feature request related to a problem? Please describe.**
Aqua does nto have any timeout in either the stage or the `aquasec scan` execution.

**Describe the solution you'd like**
A default timeout should be placed to avoid the pipeline to run infinitelly in the case of unexpected errors and enable the posibility of increasing it in the aqua stage options

**Describe alternatives you've considered**
A timeout either in the stage or in the `aquasec scan` command.

**Additional context**
The flag to add a timeout in the `aquasec scan` command is `-T`
![image](https://user-images.githubusercontent.com/26645694/165565183-8711dff3-ddf6-4782-adc5-63db6261470d.png)

**Comment by metmajer** [comment]
@braisvq1996 @hrcornejo ...and in case of a timeout send out an error email as we do for other Aqua integration related errors. Brais, we need to fix the email service in Jenkins, otherwise we do not see these issues. @jorge-romero @jafarre-viewnext this seems rather simple and could be treated as a Bug in the next white week vs. a full Shape.

**Comment by metmajer** [comment]
@braisvq1996 what about we add this to a Maintenance project?

**Comment by metmajer** [comment]
@braisvq1996 @renedupont it sounds like the response time depends on the number of requests the Aqua server needs to handle. What do you suggest as a feasible timeout?

**Comment by metmajer** [comment]
FYI @hrcornejo
